/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddressAutocomplete {
        "color": string;
        "fontFamily": string;
        "hint": string;
    }
    interface SwipeSelect {
        "color": string;
        "data": string;
        "fontFamily": string;
        "value": number;
    }
}
declare global {
    interface HTMLAddressAutocompleteElement extends Components.AddressAutocomplete, HTMLStencilElement {
    }
    var HTMLAddressAutocompleteElement: {
        prototype: HTMLAddressAutocompleteElement;
        new (): HTMLAddressAutocompleteElement;
    };
    interface HTMLSwipeSelectElement extends Components.SwipeSelect, HTMLStencilElement {
    }
    var HTMLSwipeSelectElement: {
        prototype: HTMLSwipeSelectElement;
        new (): HTMLSwipeSelectElement;
    };
    interface HTMLElementTagNameMap {
        "address-autocomplete": HTMLAddressAutocompleteElement;
        "swipe-select": HTMLSwipeSelectElement;
    }
}
declare namespace LocalJSX {
    interface AddressAutocomplete {
        "color"?: string;
        "fontFamily"?: string;
        "hint"?: string;
    }
    interface SwipeSelect {
        "color"?: string;
        "data"?: string;
        "fontFamily"?: string;
        "value"?: number;
    }
    interface IntrinsicElements {
        "address-autocomplete": AddressAutocomplete;
        "swipe-select": SwipeSelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "address-autocomplete": LocalJSX.AddressAutocomplete & JSXBase.HTMLAttributes<HTMLAddressAutocompleteElement>;
            "swipe-select": LocalJSX.SwipeSelect & JSXBase.HTMLAttributes<HTMLSwipeSelectElement>;
        }
    }
}
